return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	build = ":TSUpdate",
	branch = "master",
	main = 'nvim-treesitter.configs',
	opts = {
		ensure_installed = {
			"bash",
			"query",
			"c",
			"diff",
			"editorconfig",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"javascript",
			"typescript",
			"jsdoc",
			"json",
			"jsonc",
			"lua",
			"luadoc",
			"make",
			"markdown",
			"markdown_inline",
			"python",
			"ql",
			"ssh_config",
			"toml",
			"vim",
			"vimdoc",
		},
		sync_install = false,
		auto_install = true,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = false,
		},
	},
}
